# Generated by Django 4.2.7 on 2023-12-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDB', '0002_vehiculo_vendedor_rename_estudiante_cliente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
