# Generated by Django 4.2.7 on 2023-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDB', '0005_delete_vehiculostock_delete_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometros',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
