# Generated by Django 4.2.7 on 2023-12-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDB', '0006_vehiculo_kilometros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='kilometros',
        ),
    ]
