# Generated by Django 4.2.7 on 2023-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDB', '0007_remove_vehiculo_kilometros'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometros',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
